### ISSUE TITLE
Two TTF merge issue

### ISSUE THREAD

**Issue by XQDD** [littlevgl/lv_font_conv#14]
### Text
```text
run 中文你好速度过快及时打款过来就可怜见 the test!\xEF\x8A\x87
```
![image](https://user-images.githubusercontent.com/20871761/60696865-2ded4000-9f1a-11e9-9040-f9232a8ddb1c.png)

---
### The lost icon
![image](https://user-images.githubusercontent.com/20871761/60693785-30e23380-9f0e-11e9-8272-048b144ae60e.png)

----
### configuration
![image](https://user-images.githubusercontent.com/20871761/60696912-5a08c100-9f1a-11e9-85a9-ed321d6ca0f9.png)

[temp.zip](https://github.com/littlevgl/lv_font_conv/files/3361040/temp.zip)

**Comment by kisvegabor** [comment]
It was a limitation in lvgl. There are too many characters in the font.

I've added `LV_FONT_FMT_TXT_LARGE`  option. If you enable it in `lv_conf.h` LittlevGL will handle large fonts too.

**Comment by XQDD** [comment]
fix at https://github.com/littlevgl/lvgl/commit/2dce4407c74e5aac784c6902080f1eb1ec4ef104
