### ISSUE TITLE
Show error message in the online converter

### ISSUE THREAD

**Issue by kisvegabor** [littlevgl/lv_font_conv#17]
Hi,

I'd like to display an `alert` if the converter finds an error, like "Font "TAHOMA.TTF" doesn't have any characters included in range 0xe80-0xeff".

Is there a way to get the error message printed into the console?

**Comment by puzrin** [comment]
See https://github.com/littlevgl/lv_font_conv/blob/master/lv_font_conv.js#L11 and https://github.com/littlevgl/lv_font_conv/blob/master/lib/collect_font_data.js#L22

Errors of custom type "AppError" are processed as "logical" (only text displayed). Others are considered as crashes. You may do something similar.

Is it what you asked about?

**Comment by kisvegabor** [comment]
So do you suggest to locally change [ console.error(err.message.trim());](https://github.com/littlevgl/lv_font_conv/blob/master/lv_font_conv.js#L13) to `alert(err.message.trim())` (or something similar)?

**Comment by puzrin** [comment]
You can wrap this to try/catch and do something with exception:

https://github.com/littlevgl/lv_font_conv/blob/master/web/index.js#L121

Is this what you are asking about? Not sure i understand you right.

**Comment by kisvegabor** [comment]
Thank you, it's working. See https://github.com/littlevgl/lv_font_conv/pull/18
