### ISSUE TITLE
CLI spec

### ISSUE THREAD

**Issue by puzrin** [littlevgl/lv_font_conv#2]
Font params are grouped to current font until new font option found.

Common:

- `-s` - output font size
- `-o` - output file path
- `-b`, `--bpp` - bits per pixel
- `-c`, `--compress` - 'auto', compression algorythm (TBD)
  - RLE in general, but details depent on bpp & font size
- `--format` - output format, useful for debug & experiments
  - `json` - intermediate, to connect loader and writers
  - `images` - write each glyph to separate file, useful to check result.
  - TBD

Fonts:

- `--font` - local path or URL (may be used multiple times)
- `-r` - single glyph or range, + optional mapping; belongs to previously declared `--font`)
    - `-r 0x1F450` - single value, dec or hex format
    - `-r 0x1F450-0x1F470` - range
    - `-r 0x1F450=>0xF005` - single glyph with mapping
    - `-r 0x1F450-0x1F470=>0xF005` - range with mapping
- `--symbols` - list of characters to copy (instead of numeric format in `-r`)

**Comment by kisvegabor** [comment]
> Do we need options for weight/italic or those are stored in separate files?

Handling them as separate files are more generic.

> How to define glyph codes remap?

Why do we need font remap?

> how to define chars directly (without codes)

How do you mean it?

> named sets (ascii, latin, cyrilic, ...)?

Would be nice. `-set ascii` ? Can replace `-range`.

What is still required is to define the characters individually. E.g. `-list "a, b, k, j"`

**Comment by puzrin** [comment]
> Why do we need font remap?

Because if you use FontAwesome, you may wish to change codes to unicode standard, to make icons visible in source code.

> How do you mean it?

Something like `list` arg in old convertor.

> Would be nice. -set ascii ? Can replace -range.

The question is, where to take useful set names

**Comment by kisvegabor** [comment]
> Because if you use FontAwesome, you may wish to change codes to unicode standard, to make icons visible in source code. This looks more nice than "SYMBOL_SMALL_ARROW_LEFT", "SYMBOL_SMILE" and so on.

I see and agree.

> Something like list arg in old convertor.

Simply: `-list "a, ,b, c"` ?

> The question is, where to take useful set names

My guess it there is a maximum of 20 useful ranges and they are not changing. So we can add them manually too. I can collect them if you want.

**Comment by puzrin** [comment]
> Simply: -list "a, ,b, c" ?

I've updated CLI issue. `--symbols abcdefgsdfhsjfk`. Escaping according to shell requirements (if needed). Something like `--symbols 'abc -950'`

> My guess is there is a maximum of 20 useful ranges and they are not changing. So we can add them manually too. I can collect them if you want.

I'd like to understand principles. Right now i can imagine only 3 types of sets

- ascii (english)
- digits + dot/comma (big numbers display)
- sets by language (data from unicode CLDR)

What 20 useful ranges are you speaking about? May be you have URL where to read details?

**Comment by kisvegabor** [comment]
> I've updated CLI issue. --symbols abcdefgsdfhsjfk. Escaping according to shell requirements (if needed). Something like --symbols 'abc -950'

Looks good!



> What 20 useful ranges are you speaking about? May be you have URL where to read details?

I meant that ranges as Unicode ranges (blocks): https://en.wikipedia.org/wiki/Unicode_block
We can cover the needs of the vast majority of users with a few ranges. 

However, defining sets for numbers, upper-cased ASCII etc. sounds also reasonable

**Comment by puzrin** [comment]
> I meant that ranges as Unicode ranges (blocks): https://en.wikipedia.org/wiki/Unicode_block
We can cover the needs of the vast majority of users with a few ranges.

Ah, now see. Those blocks looks like "scripts" in unicode terms 
http://www.unicode.org/cldr/charts/latest/supplemental/languages_and_scripts.html

IMHO those ranges contains a lot of unused data. For example, if i need russian interface, i don't need all cyrilic chars, i need only russian (ru) chars.

I'd suggest consider language codes + may be "ascii" (default). Not sure where to take punctuation from. "Digits" set is very small and more simple to pass manually.

PS. And we still can generate list of chars from `lv_i18n`.

**Comment by kisvegabor** [comment]
> Ah, now see. Those blocks looks like "scripts" in unicode terms

Ah, now I see too. :smile: 

> IMHO those ranges contains a lot of unused data. For example, if i need russian interface, i don't need all cyrilic chars, i need only russian (ru) chars.

It'd be even better. But are there a good collection of used unicode characters in languages?

> PS. And we still can generate list of chars from lv_i18n.

Awesome!

**Comment by puzrin** [comment]
> But are there a good collection of used unicode characters in languages?

That's strange, but i could not find this info in CLDR and other places. Asked this question at local linux forum. May be someone knows answer.

Ranged can be found in mysql collations info, but i don't like use secondary sources.

**Comment by puzrin** [comment]
Well, such info is not available in CLDR. Something exists in `exemplarCharacters`


```xml
<characters>
	<exemplarCharacters>[а б в г д е ё ж з и й к л м н о п р с т у ф х ц ч ш щ ъ ы ь э ю я]</exemplarCharacters>
	<exemplarCharacters type="auxiliary">[{а\u0301} {е\u0301} {и\u0301} {о\u0301} {у\u0301} {ы\u0301} {э\u0301} {ю\u0301} {я\u0301}]</exemplarCharacters>
	<exemplarCharacters type="index">[А Б В Г Д Е Ё Ж З И Й К Л М Н О П Р С Т У Ф Х Ц Ч Ш Щ Ы Э Ю Я]</exemplarCharacters>
	<exemplarCharacters type="numbers">[  \- , % ‰ + 0 1 2 3 4 5 6 7 8 9]</exemplarCharacters>
	<exemplarCharacters type="punctuation">[\- ‐ – — , ; \: ! ? . … ' ‘ ‚ &quot; “ „ « » ( ) \[ \] \{ \} § @ * / \&amp; #]</exemplarCharacters>
...
</characters>
```
but still needs manual care.

Finally, it's more easy to generate optimized list of glyphs from lv_i18n phrases. Also, standard glyphs like `ascii` and `digits` are not difficult to define via `-r` & `--symbols` options.

Dropped `named sets` feature from first post.

**Comment by puzrin** [comment]
The last unsolved spec question is mapping notation. Most frequent probable use - single glyph mapping.

- `-r 0x1F450@0xF005`
- `-r 0x1F450=0xF005`
- `-r 0x1F450->0xF005`
- `-r 0x1F450=>0xF005`
- `-r 0x1F450!0xF005`
- `-r 0x1F450:0xF005`
- `-r 0x1F450#0xF005`
- `-r 0x1F450*0xF005`
- `-r 0x1F450%0xF005`
- `-r 0x1F450^0xF005`
- `-r 0x1F450$0xF005`
- `-r 0x1F450~0xF005`

**Comment by kisvegabor** [comment]
I like `0x1F450=>0xF005` It clearly shows what will be replaced with what.

**Comment by puzrin** [comment]
I tend to drop "URL" feature. Reasons:

- Initially planned for google fonts, but those are not available for direct download
  - When tried to extract via CSS parse, fonts are subsetted to slecific languages only
  - Finally, urls for google fonts CSS become very long/complicated
- Popular fonts (Roboto, FontAwesome and others) are already available in npm.
- Download can be scripted into build system (with curl, wget, ...) prior to call `lv_font_conv`)

So, download from URL will not be required for start. We can return to this in future releases, if interesting use cases will be found.

**Comment by kisvegabor** [comment]
Alright, it's not a must.

**Comment by puzrin** [comment]
Seems CLI become cluttered with short options. Tend to drop almost all (leave long only):

- `--bpp`
- `--size`
- `-o`, `--output`
- `--format`
- `--font`
- `-r`, `--range`
- `--symbols`

**Comment by kisvegabor** [comment]
Looks good!

Only one thing: Instead of `symbols`, `list` sounds more intuitive.

**Comment by puzrin** [comment]
> Only one thing: Instead of `symbols`, `list` sounds more intuitive.

I don't know, list looks too neutral about data format. List of what? Bytes, chars, cookies?

IMHO it more clear that `range` is about something numeric and `symbols` about chars. But, if you insist, i can change. Let me know.

**Comment by kisvegabor** [comment]
What about `char_list`?

**Comment by puzrin** [comment]
a) long
b) `--` and `_` looks/typed ugly when placed close. More common would be `--char-list` but `--symbols`  is more short.`

**Comment by kisvegabor** [comment]
True.
`--chars`?

**Comment by puzrin** [comment]
I don't know why, but `--symbols` fore me has more strong association with character format than `--chars`. Can't explain why. That's only personal opinion, and i don't insist.

**Comment by kisvegabor** [comment]
That's also important. People with a lot of experience can "feel" what is good or not. 

I was thinking like "what this parameter is about": it's a **list** of **characters** to use instead of the full range.  That's why I suggested _char_ and _list_ related names.

If it's not a big deal to refactor it we chose any of these names and decide it later.

**Comment by puzrin** [comment]
Updated options & fixed `-h` content to be useable.

**Comment by puzrin** [comment]
Close - no more to discuss about options. Beta with dumper implements all required things.
