### ISSUE TITLE
run on windows

### ISSUE THREAD

**Issue by mariuszmaximus** [littlevgl/lv_font_conv#21]
The lv_font_conv  application only works on linux? 
Everything works fine on linux, but I try run on windows and have problems.

Does the application have dependencies that require the Linux operating system?

**Comment by puzrin** [comment]
There are should be no linux-specific deps.

**Comment by embeddedt** [comment]
>  I try run on windows and have problems.

Please describe what problems you had.

**Comment by mariuszmaximus** [comment]
It is my first contact with node.js 
And I use README.md  ;)  

it doesn't work "npm i lv_font_conv -g"  (linux and Windows)

> npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/lv_font_conv - Not found
npm ERR! 404
npm ERR! 404  'lv_font_conv@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

it doesn't work on Windows "npx github:littlevgl/lv_font_conv -h" 

> lv_font_conv.js: error: EPERM: operation not permitted, unlink

On different version node.js I have different errors , but this method never works

But it's not so tragic, 
This method works:
git clone ...
cd lv_font_conv
npm install
node lv_font_conv.js 

It works on node-v12.10.0-win-x64 ,  node-v10.16.3-win-x64
Does not work on node-v10.16.3-win-x86
