### ISSUE TITLE
Decompression

### ISSUE THREAD

**Issue by kisvegabor** [littlevgl/lv_font_conv#22]
I've started work on decompression and it's working without prefiltering.

Problems and questions:
1. [bitmap_format](https://github.com/littlevgl/lvgl/blob/a031af4f1ebf92722f935c54e79e930bc97af022/src/lv_font/lv_font_fmt_txt.h#L193) is missing from [font_dsc](https://github.com/littlevgl/lvgl/blob/a031af4f1ebf92722f935c54e79e930bc97af022/src/lv_font/lv_font_roboto_16.c#L2239-L2249). Possible values are [here](https://github.com/littlevgl/lvgl/blob/a031af4f1ebf92722f935c54e79e930bc97af022/src/lv_font/lv_font_fmt_txt.h#L153-L156). (prefiltered option should be added to the enum)
2. It's not clear how prefiltering works. It's ok with bpp = 8 but how do you handle line ending (or even byte ending) with bpp = 2,3,4?

**Comment by puzrin** [comment]
1. Is this needed with "old" renderer or can be a part of upcoming one?

2. You are expected to create byte-aligned lines buffer for decompressed bitmap. Because you will need it anyway for fast compose. Since you know bitmap width & bpp, you can calculate rounded line length in bytes.
   - After stream is decompressed, and lines are aligned, you just apply XOR between bytes of different lines.
   - 3bits is special case, decompressed as 4bits to simplify next operations. Prefiltering will need additional masking for dummy bit.

Note, there are no direct relation between stored bpp and decompressed bpp. You can have 2 bpp compressed, but unpack as 8 bpp.

**Comment by puzrin** [comment]
Also note, 3bpp => 4bpp conversion is NOT linear (can not be done with simple shift). For example, if we get 8bpp via shift, we will never get FF and 00 in the same time.

So, whole process should look like this:

```
bitstream => unpack & realign => post-filter + mask unused bits => expand bpp
```

It's important to make non-linear expand AFTER post-filer. In this case unused bits between lines will be on the same positions, and can be masked effectively.

Here is example how 3bpp looks after unpack to 4bpp:

```
3*3 bitmap, pseudo-4bpp from 3bpp. Each line takes 2 bytes

line 0: 0111 0111 0111 0000
line 1: 0111 0111 0111 0000
line 2: 0111 0111 0111 0000
```

Here `1` means 'used bit', `0` - unused bit. When you XOR bytes between lines, you should apply 0111 0111 'and' mask. Then, do immediate "expand" and save final data to memory.

**Comment by kisvegabor** [comment]
> Is this needed with "old" renderer or can be a part of upcoming one?

It can be part of the new one as decompression will be officially supported only in v6.1.

> You are expected to create byte-aligned lines buffer for decompressed bitmap. Because you will need it anyway for fast compose. Since you know bitmap width & bpp, you can calculate rounded line length in bytes.

The spec says prefilter has ~10% extra gain. I confirmed that with Roboto 48px:
- no compress: 34640
- compress + no prefilter: 21192 (-39%)
- compress + prefilter: 18288 (-48%)

Now I handle the compressed glyph as bitstream and don't care with the line ending.  I was thinking about the implementation of prefiltering:
- needs a big buffer for the glyph itself (required anyway for decompression)
- need 2 line buffers (for byte aligned ending)
- XOR the line buffers
- copy the result in glyph buffer (trail rounded line ending)
- in case of bpp = 3 another buffer might be required to store the 3 bit version and store the converted 4 bit version into the glyph buffer.

So it looks quite complicated and needs some extra memory too. I'm not sure it's worth for a 10% gain.

I made bpp = 3 work which also has ~25% gain compared to bpp = 4. So - 40 %

**Comment by kisvegabor** [comment]
I just saw your last comment. I also realized that a simple shift is not suitable for 3 to 4 bpp conversion. I've created a lookup table for 8 possible values.

Your suggestion to store the decompressed 3 bit as 4 bit makes things a little bit easier. 
The extra complications due to line ends are still there... I'm thinking about it.

**Comment by puzrin** [comment]
> The extra complications due to line ends are still there... I'm thinking about it.

I think, if you don't try to invent one universal algorythm for all cases, and do separate functions for different bpp groups, each separate function will be not too complicated. And code overhead will be not too high.

I guess, in the end the only demanded font storage bpp will be 1bpp for OLEDs, and 3bpp for everything else.

**Comment by kisvegabor** [comment]
I've rewritten the algorithm, now it supports prefilter but I don't get a valid result. I'm not sure what is XOR-ed with what. My guess:
```
line_0_ready = line_0_decompressed
line_1_raedy = line_0_decompressed ^ line_1_decompressed
line_2_ready = line_1_decompressed ^ line_2_decompressed
```

Is that true?

**Comment by kisvegabor** [comment]
The function looks like this now:
```c
void decompress(const uint8_t * in, uint8_t * out, lv_coord_t w, lv_coord_t h, uint8_t bpp)
{
    uint32_t wrp = 0;
    uint8_t wr_size = bpp;
    if(bpp == 3) wr_size = 4;

    rle_init(in, bpp);
    decompress_line(line_buf1, w);

    lv_coord_t y;
    lv_coord_t x;
    for(x = 0; x < w; x++) {
        bits_write(out,wrp, line_buf1[x], bpp);
        wrp += wr_size;
    }

    for(y = 1; y < h; y++) {
        decompress_line(line_buf2, w);

        for(x = 0; x < w; x++) {
            bits_write(out,wrp, line_buf1[x] ^ line_buf2[x], bpp);
            wrp += wr_size;
        }

        memcpy(line_buf1, line_buf2, sizeof(line_buf1));
    }
}
```

Without prefilter it works well so the RLE part should be fine.

**Comment by puzrin** [comment]
> Is that true?

I don't remember :)

https://github.com/littlevgl/lv_font_conv/blob/master/lib/utils.js#L118-L124

As far as i see, on write prefilter goes from top to bottom. So, on load it should go in reverse order:

```
for (y = y_max - 1; y > 0; y--) {
  line[y] = line[y] ^ line[y-1] 
}
```

**Comment by puzrin** [comment]
> Without prefilter it works well so the RLE part should be fine.

That's great. I suspect unnecessary double memory access - intermediate line buffer is not needed. But... i don't like premature optimizations. Prefer to know benchmark compare with uncompressed font first. May be that's good enougth.

**Comment by kisvegabor** [comment]
Ohh, I find the issue. All works except the `!`. 
The decompressed, still not XOR-ed data looks like this:
```
03, 05, 
09, 0b, 
00, 00, 
00, 00, 
00, 00, 
00, 00, 
00, 00, 
00, 00, 
00, 00, 
00, 00, 
00, 00, 
00, 00, 
```

There is no change on the bottom of the glyph where the `.` should be.

**Comment by kisvegabor** [comment]
`""!?.,-_abc""` is rendered as: 
![image](https://user-images.githubusercontent.com/7599318/64864012-6a35ce80-d636-11e9-8d91-3e1898d7996a.png)

**Comment by puzrin** [comment]
Do you mean convertor writes buggy data? What if you run compression only, without prefilter?

**Comment by kisvegabor** [comment]
>Do you mean convertor writes buggy data?

It seems.

> What if you run compression only, without prefilter?

Work well without prefilter.

**Comment by puzrin** [comment]
Hm... compressor is one of place, 100% covered with [tests](https://github.com/littlevgl/lv_font_conv/blob/master/test/font/test_compress.js), including all possible branches. Prefilter is trivial...

No ideas. We could check generated data manually, but not right now.

Can you give me exact CLI command how do you generate that font and what convertor version you use? Need to inspect source bitmap content

**Comment by puzrin** [comment]
https://github.com/littlevgl/lv_font_conv/issues/22#issuecomment-531215991 seems your description of post-filter is correct.

**Comment by kisvegabor** [comment]
I've examined the result byte by byte and realized that the issue was in my decompressor when the 6 bit counter is 0.  Now it works well. Sorry for the noise.

---

Benchmark:
The UI below was rendered in 25 ms with uncompressed font and 46 ms with compressed. Prefilter didn't change the performance.
![IMG_20190913_151459](https://user-images.githubusercontent.com/7599318/64865403-78d1b500-d639-11e9-86ee-91422d38636c.jpg)

**Comment by puzrin** [comment]
Not bad. So, if performance matters, may be worth to make decompressor monolytic, in single pass, instead of lines split.

- One big cycle + dummy bits injection when align needed.
- 32bit accumulator as "temporary buffer", to reduce flush checks.

**Comment by kisvegabor** [comment]
My first approach (which didn't support prefiltering) was a monolithic cycle which just read the data and wrote it into the output buffer without intermediate buffers.
I've tested its performance with the same UI. It's 42 ms (compared to 46 ms). So we lost time somewhere else. I'll look into the optimization opportunities.

**Comment by puzrin** [comment]
RLE-like machinery can be done to operate in registers only. That can not give big regression. If you show me your monolytic code, i can try to search thin places.

**Comment by kisvegabor** [comment]
I suggest going with the modular version. Similarly to the monolithic version, there are no extra copies and RE processing so it shouldn't affect the performance too much. I've uploaded it to [dev-6.1](https://github.com/littlevgl/lvgl/blob/f190c781959c4cf65cbfaff2a6864d306cc10ba6/src/lv_font/lv_font_fmt_txt.c#L288-L456) branch. 

I made some calculations:
1. There are ~300 chars on the benchmark screen. 
2. The MCU runs at 160 MHz.
3. Let's assume that the characters has 13x8 size on average. 
4. It means 300x13x8 = 31,200 pixels to process.
5. We have 20 ms overhead which is 3,2M instructions. 
6. So one pixel needs 3,2M/31.2K = ~100 instructions. 

It seems fair. There are a lot of shifts, ORs, ANDs, and XOR, iterate all pixels, process RLE...

**Comment by puzrin** [comment]
> I suggest going with the modular version.

I would not agree. Such bitwise machinery is not module-frienfly, when highest performance required. It's good as first quick-done attemt, to unlock moving forward. But for performance i would suggest different approach.

1. Split decompressor to fixed-bpp variants. That will reduce used registers, and allow use simple constants/macros.
2. Use reg-buffers to load bytes, and peek/push bits there
3. Use marker bits in those buffers to easy check data ends and fetch next byte (or flush decompressed bytes).

For example, you need push 4-bits to output, and flush output sometime when collected enougth.

1. Set output buffer (uint32) register's content = 1 (tracking bit)
2. create macro `PUSH_4` (shift 4 bits to buffer + decrease line pixels counter)
3. Check 24-th bit of buffer - if set, flush 3 bytes.

The same for input. Create PEEK_1, PEEK_2, ... it should check if value > XX (data bordered with tracking bit) - do peek. If not - need to fill buffer with next byte from bitstream.

Tracking bits allows easy static checks and do not occupy registers for variable.

That will fit into single (or double, x/y) cycle well, with everything needed and few vars.

Regarding to modular code - i do not know methods how to improve such approach with small iterations, with guaranteed result. I know how to write optimized algorythms :).

**Comment by puzrin** [comment]
https://github.com/littlevgl/lv_font_conv/commit/cb3024654a43bd79b7c95482c34e2c774585cb83

Added missed `.bitmap_format` field. Now in `dev` branch.

**Comment by kisvegabor** [comment]
I made some more test. 
- Using fix values where possible the rendering time was reduced only by 3 ms.
- The write itself takes 6 ms out of 20 ms but fix values reduced 6 ms only to 5 ms. 
- So probably word write/read could have some benefits.

However, I've realized the following:
- compression will always cause performance loos
- large fonts can be compressed effectively (15%  at 16 px, 30% at 28 px)
- typically you have only a few large fonts on your UI, therefore I've changed the test UI like this
![IMG_20190914_103840](https://user-images.githubusercontent.com/7599318/64905726-bfc4b680-d6dc-11e9-9596-278b0444dfbe.jpg)

If the large font (28 px) is compressed the rendering time is 36 ms, with uncompressed 32 ms. So IMO in this more life-like scenario there is too small overhead to spend time on the optimization.

**Comment by puzrin** [comment]
My opinion is, that properly implemented RLE can be almost transparent. But since i'm not going write "better" C decompressor, it would be not honest to criticize your work too much. I can only share my knowlege of technical aspects and let you decide how y use (or ignore) those.

Personally, my 2 hobby projects have smaller screens (80*160 & 320*200) with few text, and current performance "regression" will not become critical there.

**Comment by kisvegabor** [comment]
As it's not critically bad (usually working without serious performance loss) I'd like to deal with higher priority things now.

So I think this issue can be closed.
Thank you for your help!

**Comment by puzrin** [comment]
@kisvegabor FYI, on real device (my dispenser project), compressed fonts are several time slower. On "animated" list scroll i see 2 slow refreshes. With disabled compression animation is not ideal too, but i don't see flickering.

**Comment by kisvegabor** [comment]
Can you make a video to show the difference?

**Comment by puzrin** [comment]
I never created video. Would prefer to do so only if can't be avoided. Screen slowly redraws from top to bottom. For animation time (150ms) this happens twice, instead of slide. But visually this looks much slower. ~ about 0.5s for each redraw.

> BTW, what is the size of your display and list? And how fast is your MCU?

https://github.com/puzrin/dispenser - there is screenshot from sim in readme

- stm32f072cbt8 @ 48 MHz (USB from internal src)
- Display 80*160px, buffer 20 lines (tried 40, 60 - no significant improve)
- List has 6 items, 4 visible at once, up to 5 on scroll. https://github.com/puzrin/dispenser/blob/dev/src/screen_dose.cpp. Single object per list item + custom drawer with 2 `lv_draw_label()` calls.

**Comment by kisvegabor** [comment]
It's surprisingly slow. I drive a 240x240 display  (4.5 times larger than yours) with a 100 MHz MCU at 20-30 FPS with a lot of animations.  

In `platform.ini` I don't see any optimization settings. Have you enabled optimization somewhere else?

**Comment by puzrin** [comment]
> In platform.ini I don't see any optimization settings. Have you enabled optimization somewhere else?

It should be `-Os`, you can check via verbose build (menu -> terminal -> run task).

**Comment by kisvegabor** [comment]
I see.

Two more questions came to my mind (sorry for the evasive answers but I'd like to understand why is it so slow.):
1. I haven't found the display's SPI configuration. What is its speed?
2. Once you use DMA in `disp_flush`, [here](https://github.com/puzrin/dispenser/blob/master/hal/stm32f072cb/app_hal.cpp#L149-L150) have you tried two 10 lines buffer instead of one 20 lines?

**Comment by puzrin** [comment]
- SPI clock is 18MHz
- Driver has DMA mode only https://github.com/puzrin/dispenser/blob/master/hal/stm32f072cb/st7735.cpp#L119

**Comment by kisvegabor** [comment]
Could you try it with 2 buffers and -O3 optimization?

**Comment by kisvegabor** [comment]
> Do i need only pass second buffer into lv_disp_buf_init() to activate double buffering? I see no visual difference at all

Yes, you only need to pass a second buffer.

> -O3 - may be very small improvement, not worth to pay attention. In general - doesn't help and eat much more flash memory. I had to disable useful monitoring features to fit into 128k.

I see.

I understand your problem. I still wonder how could I achieve 20-30 FPS on 100 MHz with a 5 times larger screen using "hard-core" effects. Can you show where you initialize the styles of the list?

**Comment by puzrin** [comment]
- [here](https://github.com/puzrin/dispenser/blob/master/src/app.cpp#L125-L164) i initialize styles
- [here](https://github.com/puzrin/dispenser/blob/master/src/screen_dose.cpp#L168-L203) create styled list & and [here](https://github.com/puzrin/dispenser/blob/master/src/screen_dose.cpp#L14-L54) draw texts inside (via custom drawer, to save RAM)

**Comment by kisvegabor** [comment]
I can't see anything obvious. All looks correct. It seems that's what we can expect from this MCU. 

> I say, code should be "normalized" first, to apply well known RLE decoding approaches. Because discussing non-normalized code is reinventing wheel and ineffective spend of time.

Can you show an example of "well known RLE decoding approaches" which can be applied for this algorithm?

**Comment by puzrin** [comment]
> Can you show an example of "well known RLE decoding approaches" which can be applied for this algorithm?

No. I don't keep links to proofs in head, because when i write code i should know how make best choice, not how to prove it :). That's a background experience from project like [pako](https://github.com/nodeca/pako), when i studied a lot of articles because it was interesting.

I can only explain general principles:

- Memory access is expensive (at least 3 cycles with stm32), register ops are cheap (1 cycle).
- Too many vars may not fit in registers.
- Non-inlined functions in hot path is a pain (i don't know if your bit extractors-writers are inlined or not).

There are more thin factors (jumps), but this 3 are most critical.

That may produce sometime amazing results on some CPU, because decompresser needs read LESS memory than direct memory copy.

All optimizations i described before just implement this approaches:

- aligned & wide memory access (reduce io).
- const shifts instead of var shift (reduce local vars, save registers).
- macros for read/write instead of functions (no subcalls).

Missed points for our particular case are:

- table-based 3bpp => 4bpp conversion (may be local math will be better)
- prefilter reverse may be costy, may be need option to disable
- font-convertor probably needs option to generate aligned bitmaps for 32-bit read. This could cause notable losses for ordinary fonts, but ok for subpixel fonts.

**Comment by kisvegabor** [comment]
I can take look with these in mind when the styles are ready.

**Comment by puzrin** [comment]
That would be nice. As i said, that's not critical and not urgent for me - my project can fly with uncompressed fonts. But it would be pleasant if decompresser reaches state "nothing left to improve".

PS. As quick check, i'd suggest to look in debugger, are reader/writer functions in your implementation inlined or not with `-Os`. If not - i guarantee performance improve 2x at least (without counting prefilter, that's a separate story).
