### ISSUE TITLE
Pending issues in 0.2.0 (FreeType) version

### ISSUE THREAD

**Issue by puzrin** [littlevgl/lv_font_conv#23]
This version is currently in `dev` branch. Please, post here all found bugs.

- All previously reported "broken" fonts should work now.
- Better look for many fonts (forced hinting)
- May be... even better look for monochrome output (special monochrome hinter used)

Pending things are internal, not visible to end users:

- [x] Code cleanup, drop opentype.js use everywhere
- [ ] Review FreeType calls, is anyone has experience
- [ ] Improve build scripts for FreeType (current ones are ugly)

**Comment by puzrin** [comment]
We removed `opentype.js` use almost everywhere. But still use it to extract kerning pairs from `GSUB` table, because FreeType does not support that. Many modern fonts don't have `kern` tables, and use `GSUB` only. Example - Roboto font.

**Comment by puzrin** [comment]
Did anyone tried this? I'd like to make a release. CLI should be compatible with 6.0.

**Comment by kisvegabor** [comment]
I've just tried and works well.

Only [this issue](https://github.com/littlevgl/lv_font_conv/issues/15#issuecomment-531457889) remains but as we discussed it's an ecceptabée trade-off and can be mitigated with different hinting.

**Comment by puzrin** [comment]
Could you clarify, why glued "rt" is invalid? Are you sure Roboto is NOT designed/kerned this way? Previous convertor can not be proof of correctness.

See enlarged screenshot of this message preview:

![rt](https://user-images.githubusercontent.com/319465/65577801-32575100-df7d-11e9-9d51-316cbc07e91a.png)

**Comment by kisvegabor** [comment]
You are right. It seems really this is the intended behavior. In Libre Office it looks like this:
![image](https://user-images.githubusercontent.com/7599318/65578021-5020b800-df75-11e9-95d5-44fefe7ebb60.png)

Also very close. Than all fine! :slightly_smiling_face:

**Comment by puzrin** [comment]
Released 0.2.0

**Comment by kisvegabor** [comment]
Awesome!
