### ISSUE TITLE
Endianness of the binary output.

### ISSUE THREAD

**Issue by dutchmartin** [littlevgl/lv_font_conv#24]
While trying to [read the binary format](https://github.com/dutchmartin/lv_font_reader), I realized that my readings are wrong because the cli outputs the binary in little endian (which is the default in [the bitbuffer](https://github.com/inolen/bit-buffer) used here). I would prefer to make it big endian if it is possible.

Would it be possible to change this?

**Comment by puzrin** [comment]
https://github.com/littlevgl/lv_font_conv/blob/master/lib/font/table_glyf.js#L37

It does not use defaults. As far as i remember, bits order is optimal, and it's already used in lvgl without problems. If you request breaking change - need seruous reasons for that.

**Comment by dutchmartin** [comment]
Thank you for you time to look at my issue.
Maybe I am wrong, but I am trying to understand how I should read the binary output of the converter since I like to make it work in Rust.
I tried to create a program that reads in the binary file with the following results for each endianness:
big endian:
```
[src/main.rs:13] record_size = 738197504
[src/main.rs:15] head = 1751474532
[src/main.rs:17] version = 256
[src/main.rs:19] additional_tables = 0
[src/main.rs:21] font_size = 768
[src/main.rs:23] ascent = 7680
[src/main.rs:25] descent = 5376
[src/main.rs:27] typo_ascent = 64255
[src/main.rs:29] typo_decent = 6144
[src/main.rs:31] typo_line_gap = -1281
[src/main.rs:34] min_y = 0
[src/main.rs:36] max_y = 64255
```
little endian:
```
[src/main.rs:13] record_size = 44
[src/main.rs:15] head = 1684104552
[src/main.rs:17] version = 1
[src/main.rs:19] additional_tables = 0
[src/main.rs:21] font_size = 3
[src/main.rs:23] ascent = 30
[src/main.rs:25] descent = -21
[src/main.rs:27] typo_ascent = 65530
[src/main.rs:29] typo_decent = 24
[src/main.rs:31] typo_line_gap = -6
[src/main.rs:34] min_y = 0
[src/main.rs:36] max_y = 65530
```

You can view the c output for that same font [here](https://gist.github.com/dutchmartin/9e995905e54a008f4d7c2844dc0e2cff) and view the bits of the binary [here](https://gist.github.com/dutchmartin/2f7483c35f35811e16e9a4d2ae632352)

Looking at the outputs above, I assume the binary is written in little endian. But is that true?
Also, I would like to know a way how i can validate the read values.

That said:
I don't want to make breaking changes (it could be hidden under a cli parameter), but currently the support for little endian on embedded Rust is poor/non-existent. Also, if i would write a library to read it the way it is, it would induce a runtime cost for reversing the bits.

**Comment by puzrin** [comment]
https://github.com/littlevgl/lv_font_conv/blob/master/lib/font/table_head.js

If you ask about 2-bytes and 4-bytes numbers, those are LE everywhere.

> Also, if i would write a library to read it the way it is, it would induce a runtime cost for reversing the bits.

I don't understand you. LE & BE do not change bits order. They change BYTES order.

- Anyway, it worth read those "manually", because lib should nod depend on MCU endianess.
- Cost of those operation is very low. Any talks about speed without appropriate benchmarks are "waste of time".

I'd suggest to make something working first. Then, after battle testing, if you still has issues and still think endianess is important, we can return to this question.

**Comment by embeddedt** [comment]
Closing after 7 days is a bit aggressive. I'd suggest to wait another week.

**Comment by puzrin** [comment]
I see no reasons to wait, because no arguments (with proofs) about added value were provided.

**Comment by dutchmartin** [comment]
Closing the issue is fine, but maybe we could add the information about the endianness to the [specification](https://github.com/littlevgl/lv_font_conv/blob/master/doc/font_spec.md) so others just know it is LE.

**Comment by puzrin** [comment]
Hm... I thought it's obvious, because LE is most used everywhere.

But after digging OpenType docs, found they use BE https://docs.microsoft.com/en-us/typography/opentype/spec/otff#data-types.

**Comment by puzrin** [comment]
https://github.com/littlevgl/lv_font_conv/commit/7e271bf73bd71d812dbb5217328a86ab9d5f0ffe added

**Comment by dutchmartin** [comment]
Thank you @puzrin
