### ISSUE TITLE
Microsoft Yahei will cause errors starting from Ver0.2.0: "abort(OOM). Build with -s ASSERTIONS=1 for more info."

### ISSUE THREAD

**Issue by jimaobian** [littlevgl/lv_font_conv#29]
Hi,
It seems to work on Ver0.1.0 but not on above. Would you like to look into it?  Thank you.
Here is the font:
[msyh.ttf.zip](https://github.com/littlevgl/lv_font_conv/files/3930408/msyh.ttf.zip)

**Comment by puzrin** [comment]
Seems wasm build has memory limits by default, and font size is too big. Should be fixed in master. Please test and let me know.

**Comment by jimaobian** [comment]
Solved. Thank you!

**Comment by puzrin** [comment]
Thanks for report. Released 0.4.1.

@kisvegabor consider update website with new version.

**Comment by kisvegabor** [comment]
> consider update website with new version.

Updated, thank you!
