### ISSUE TITLE
Binary file name?

### ISSUE THREAD

**Issue by puzrin** [littlevgl/lv_font_conv#3]
`lv_font_converter` :)

Any better ideas/reasons?

**Comment by embeddedt** [comment]
@puzrin The only issue I would have (and it's minor) is that the name is a bit longer than I would be used to for a CLI tool.

**Comment by puzrin** [comment]
Hm... never noticed for many years, i always type with autocomplete by `tab`

**Comment by kisvegabor** [comment]
lv_cfont?

**Comment by puzrin** [comment]
lv_font?

**Comment by embeddedt** [comment]
@puzrin `lv_font` does not give the user the impression that it's a convertor tool. I suppose if they always get it from this repository it doesn't really matter though.

**Comment by puzrin** [comment]
lv_font_build?

**Comment by puzrin** [comment]
lv_font_create?

**Comment by kisvegabor** [comment]
lv_fontconv?

**Comment by puzrin** [comment]
lv_font_conv? - more readable in scripts

**Comment by embeddedt** [comment]
@kisvegabor @puzrin I like `lv_font_conv`.

**Comment by puzrin** [comment]
I'm ok woth `lv_font_conv`.

If no objections, could you rename repo, then press sync in travis-ci and make sure repo is enabled after rename?

**Comment by embeddedt** [comment]
@puzrin Done.

**Comment by kisvegabor** [comment]
Maybe I'm a little bit late, but I also agree with "lv_font_conv".
