### ISSUE TITLE
Error: error in FT_New_Memory_Face: 2

### ISSUE THREAD

**Issue by BrianPugh** [littlevgl/lv_font_conv#31]
Currently a WOFF I made (pixel-perfect symbols that were crappily made in FontForge for a low res monochrome oled display. Only reason I'm saying this is that there might be errors within the font like self-intersecting symbols) no longer works using the online font converter. This same WOFF file worked previously (I believe I last used the converter on Aug 17, 2019).

Settings:
Name: `jolt_symbols`
Size: `8`
Bpp: `1`
Compression? `yes`
Range: `0xF000-0xF00D`

WOFF file (zipped for GitHub compatibility)
[jolt_symbols_old.zip](https://github.com/littlevgl/lv_font_conv/files/3965658/jolt_symbols_old.zip)

The popup error dialog says "Error: error in FT_New_Memory_Face: 2"

**Comment by embeddedt** [comment]
August was before the internal renderer was switched from OpenType.JS to FreeType, so chances are your font is incompatible with FreeType for some reason. Unfortunately I don't know enough about the internals of the font converter to give any further information.

**Comment by puzrin** [comment]
@BrianPugh AFAIK, problem may be only with self-cross contours. When you draw multiple "correct" contours and those touch or overlap - that's ok.

I did this thing: opened your file FontForge, then saved as TTF via "Create Font". So:

- Provided WOFF file crashes with code 2, as been reported.
- Resaved TTF works.

If that's ok - i'd prefer to close issue. In other words - nobody interested spend time for debug just to know one more way to create bad font :). As far as i remember, i had issues with FF's woff format compatibility when did fontello. If you draw in FF - just save your work as TTF.

If you need other font formats - use standalone tools instead (see [ttf2woff](https://github.com/fontello/ttf2woff), [wawoff2](https://github.com/fontello/wawoff2) or native C projects)

**Comment by puzrin** [comment]
> Unfortunately I don't know enough about the internals of the font converter to give any further information.

https://github.com/littlevgl/lv_font_conv/blob/master/lib/freetype/index.js#L96 - error happens on attempt to load font into FreeType, before process concrete glyphs. Probably, FF's woff has compatibility issues. 

IMO we can bury this silent :). TTF works.

**Comment by BrianPugh** [comment]
This solves my problem, thanks guys!
