### ISSUE TITLE
Option to define `lvgl.h` path

### ISSUE THREAD

**Issue by puzrin** [littlevgl/lv_font_conv#33]
https://github.com/littlevgl/lvgl/blob/master/src/lv_font/lv_font_roboto_12.c#L1

Currently path to `lvgl.h` in font file is hardcoded. That's not convenient for outer fonts. For example, i have to [fix path with sed](https://github.com/puzrin/dispenser/blob/dev/package.json) in my projects. Can we have something more comfortable? For example, i could add option to define alternate path.

Questions:

- Do you think this needs fix at all?
- Is it possible to fix issue without new option?
- If new option is the only choice, what is the good name? `--lvglh` looks a bit strange for me (but i'll be ok with it).

/cc @kisvegabor, @embeddedt

**Comment by embeddedt** [comment]
> If new option is the only choice, what is the good name?

What about `--lv_include`?

**Comment by embeddedt** [comment]
> Is it possible to fix issue without new option?

Add the `lvgl` directory to your include path so that `lvgl.h` is accessible without requiring a prefix.

**Comment by puzrin** [comment]
https://github.com/littlevgl/lv_font_conv/blob/master/lib/writers/lvgl/lv_font.js#L37

That will not help. Path is hardcoded to "recommended" directory struct by lvgl doc. I have to patch it to make work as you described (with lvgl dir in include path)

**Comment by puzrin** [comment]
> What about `--lv_include`?

May be. Looks nice.

**Comment by kisvegabor** [comment]
When I've added the test I needed to make the path of `lv_conf.h` definable. I've solved it [this way](https://github.com/littlevgl/lvgl/blob/dev-7.0/src/lv_conf_internal.h#L13-L21).

I've found that it's a hell to pass `"` in command-line arguments (e.g. `-D\\\"lv_conf.h\\\"`) so I added the `"` internally.

I'd use `LVGL_PATH` which defines only the path to the `lvgl` folder and `/lvgl.h` is appended in compile time. It gives more flexibility because this define can be used for other files too (not sure there will be other files to use with though)

**Comment by puzrin** [comment]
IMO it's overkill to add path into PATH and duplicate it in guard.

> It gives more flexibility because this define can be used for other files too (not sure there will be other files to use with though)

My approach is to reject all "in advance" features, until multiple real cases confirmed and considered useful. Uncontrolled extensions spoils api very fast.

We could have:

- "lvgl.h" as default for custom (external) fonts, because that will be searcheable (this is optional, if you think `../../lvgl.h` is better)
- option to set custom path to file, without `"`. Will look like `--lv_include '../../lvgl.h'`

**Comment by kisvegabor** [comment]
> My approach is to reject all "in advance" features, until multiple real cases confirmed and considered useful. Uncontrolled extensions spoils api very fast.

I don't insist on it. I also don't know other case then including `lvgl.h`

> option to set custom path to file, without ". Will look like --lv_include '../../lvgl.h'

Where does `--lv-include` cames from? In PIO you also use `-DLV_INCLUDE` compiler flags, don't you?

**Comment by puzrin** [comment]
> Where does `--lv-include` cames from? In PIO you also use `-DLV_INCLUDE` compiler flags, don't you?

https://github.com/puzrin/dispenser/blob/dev/platformio.ini#L17 i use `-D LV_CONF_INCLUDE_SIMPLE`. LVGL package dir added to search path automatically.

`--lv-include` appeared because i'd like include header without path, but someone can have different opinion.

**Comment by kisvegabor** [comment]
> --lv-include appeared because i'd like include header without path, but someone can have different opinion.

I see but why the `--lower-case` format instead of `DUPPER_CASE`?

**Comment by puzrin** [comment]
> I see but why the `--lower-case` format instead of `-DUPPER_CASE`?

I think, that's personal preference. `-DUPPER_CASE` pollute global config IMO. With `--lower-case` i can keep details separate.

Since font files are generated, i'd prefer to solve issues on generation stage and not propagate without need.

**Comment by kisvegabor** [comment]
For the whole time, I thought you meant a "definable" path in lvgl, not in the font converter. 
In this case, `--lv-include` is fine for me!
