### ISSUE TITLE
Support 8 bpp

### ISSUE THREAD

**Issue by kisvegabor** [littlevgl/lv_font_conv#36]
Hi,

How difficult would it be to support 8 bpp? 
It's not reasonable for "normal"  texts, but 8bpp could be used nicely for masking if the letters are considered as alpha maps.

**Comment by puzrin** [comment]
AFAIK 8bpp support exists inside, but was disabled to avoid introducing "useless option".

> It's not reasonable for "normal" texts, but 8bpp could be used nicely for masking if the letters are considered as alpha maps.

I'm not sure i can understand how is that related to fonts. Could you explain?

**Comment by kisvegabor** [comment]
> I'm not sure i can understand how is that related to fonts. Could you explain? Yes, that's technically possible, but what a benefits from such "strange" font use?

The drawing system of v7 can handle masks. They can be computed in real time (e.g. crop outside of a rounded rectangle) or the mask can come from alpha maps. The 8-bit glyphs can be directly used as masks. A use case, for example, to mask out a letter or an entire text from a gradient background or an image.

Besides, I was playing with the realtime scaling of bitmaps. The quality is no so good for now but could be enough for animations and effects. (Not sure if it's a viable thing). And it'd be faster to scale byte-aligned maps.

**Comment by puzrin** [comment]
> The 8-bit glyphs can be directly used as masks. A use case, for example, to mask out a letter or an entire text from a gradient background or an image.

> And it'd be faster to scale byte-aligned maps.

As far as i understand, that's not storage (writer) issue. Writer [convertor] saves data "precise enough". But you can unpack 4bpp as 8bpp if you wish. The same way as 3bpp unpacked to 4bpp.

**Comment by kisvegabor** [comment]
By "precise enough" do you mean the 4 bpp should be precise enough?
If so, probably it's true, but masks use 0-255 values. The conversion from 4 to 8 bpp would have an unnecessary computation cost.

**Comment by puzrin** [comment]
> The conversion from 4 to 8 bpp would have an unnecessary computation cost.

That's just a table of 16 bytes lookup. I can enable 8bpp if you wish. But are you sure everything else is so fast, that such specific deep-coupled opimization should be used?

**Comment by kisvegabor** [comment]
> That's just a table of 16 bytes lookup. I

Plus getting masking/shifting half-bytes from the 4bpp bitmap. Besides the result should be stored in another buffer. So it seems much complicated than using an 8bit map directly. 

> But are you sure everything else is so fast, that such specific deep-coupled opimization should be used?

I see it quite straight forward. Alpha masks contain alpha values from 0-255. So IMO it's rather natural than hacky. But you might argue with this. :slightly_smiling_face: 

> I can enable 8bpp if you wish.

Then please enable it if it's not a big problem.

**Comment by puzrin** [comment]
> But you might argue with this.

With my experience of code optimizarions, i consider discussing performance issues without benchmarks not productive. From my point of view, it worth to postpone everything and create tests/benchmarks prior to continue. If not - it's more simple for me to just enable 8bpp, despite i don't like this idea.

**Comment by puzrin** [comment]
See https://github.com/littlevgl/lv_font_conv/tree/dev, https://github.com/littlevgl/lv_font_conv/commit/1702ef47bbbaca89a8f7cd4b2225403af08f202d. I can release it anytime when you wish.

Also note, web version have no 3bpp option, and i did not updated with 8bpp -  don't know how should it be. https://github.com/littlevgl/lv_font_conv/blob/dev/web/content.html#L54-L56

**Comment by kisvegabor** [comment]
Thank you, please release it. 

I've just added the 3 bpp and 8 bpp options: https://github.com/littlevgl/lv_font_conv/commit/60b6f5c75704e36ac90c34c59971a8a642467438

**Comment by kisvegabor** [comment]
Thank you!
