### ISSUE TITLE
Subpx rendering in v7

### ISSUE THREAD

**Issue by gmomchilov** [littlevgl/lv_font_conv#39]
I can see that converting TTF fonts with subpx rendering is only available for lvgl v6.0 - is that correct?

lv_table_head.js, lines 73-75 :

#if !(LVGL_VERSION_MAJOR == 6 && LVGL_VERSION_MINOR == 0)
    .subpx = ${subpixels},
#endif

Using LVGL v7 and setting .subpx to anything different than LV_SUBPX_NONE produces bad results on the display with both

#define LV_FONT_SUBPX_BGR 1

and

#define LV_FONT_SUBPX_BGR 0

**Comment by embeddedt** [comment]
> I can see that converting TTF fonts with subpx rendering is only available for lvgl v6.0 - is that correct?

No; it should be available in 6.1+ (including 7.0). That condition is just to exclude 6.0. What font and settings are you using?

**Comment by gmomchilov** [comment]
When I call the converter with --subpx, it generates

**Comment by embeddedt** [comment]
I believe you should be calling it with `--lcd` (for horizontal subpixels) or `--lcd-v` (for vertical subpixels). `--subpx` doesn't seem to be present in the code. That's probably why it's generating `LV_FONT_SUBPX_NONE`.

Manually changing the value won't be enough as the subpixel information will be still missing from the font. It chooses the value in `.subpx` based on what it actually output.

**Comment by gmomchilov** [comment]
Yes, using the python script with those arguments doesn't work, as you mentioned but it works with --lcd directly to the lv_font_conv lib.
