### ISSUE TITLE
Built-in symbol fonts

### ISSUE THREAD

**Issue by kisvegabor** [littlevgl/lv_font_conv#4]
Continue the discussion of built-in symbols here (#1)

**Comment by puzrin** [comment]
**Potential problem**

- As far as i understand, current "mapping" feature allow to generate any desired combination of data.
- But current font format is mixture of data + functions. This is very fragile approach, because data become not serializable. This reduces transparency with third-party tools (and just a "bad practice").

I guess, initial indent was to optimize unused code. But price is too high. At first glance, i could suggest several things:

- Estimate real saving, and if it's small - don't care about it.
- Use `#define` in config, to isolate unused code.

That's my noob's point of view. May be i don't know something important - fix me, if i'm wrong.

**summary**

Try to accept principle "don't mix data with code" and try to change font content to satisfy it.

May be that's not possible (i don't know 100%), but we should try.

**Comment by kisvegabor** [comment]
Now the built-in symbols have two special attributes:
1. They are remapped from a spare space to a continuous with `LV_SYMBOL_...` defines. But it's not really required in general. Leaving them as sparse can work too if UTF8 encoding is enabled. 
2. However, if UTF8 is not enabled the symbol fonts are mapped form `0xC0` to fit into one byte. 

Now a symbol font support both UTF8 and non-UTF8 configuration via defines. And this "hack" is the root of the issues in this case.  

Always enabling the UTF8 support would solve the issue. Its performance and memory impact should be minimal. @embeddedt What do you think about it?

Making the symbol fonts generic (normal sparse fonts) would make easier to add custom symbols. Some user already asked questions about it because the current use of symbols are really not trivial.

**Comment by embeddedt** [comment]
@kisvegabor I think leaving UTF-8 on all the time will be fine.

**Comment by puzrin** [comment]
> Now a symbol font support both UTF8 and non-UTF8 configuration via defines. And this "hack" is the root of the issues in this case.

Probably i don't understand well difference between UTF8 and non-UTF8 in context of font.

Font is just a way to pack tuples { code, image } in effective way. This should not depend on encoding. Also, all params like sparse/continuous & RLE compression type should be selected automatically, based on list of codepoints & images content.

Where is the place for UTF8 here?

**Comment by embeddedt** [comment]
(Quoting @kisvegabor):

> If UTF8 is not enabled the symbol fonts are mapped form 0xC0 to fit into one byte.

This remapping is done by the font converter. It's necessary because when UTF-8 is disabled, the symbols would be out of range since they use Unicode code points greater than one byte.

**Comment by puzrin** [comment]
I also suggest to consider font as "binary blob" (now it's a C code with structs and so on).

This is more formal approach, helping a lot to quickly check real binary size without compiler. Very useful for experiments, when we need check new compression algorythms (or find most effective from existing list).

See how fonts are stored in u8g2 https://github.com/olikraus/u8g2/blob/master/csrc/u8g2_fonts.c (just an example of binary data)

**Comment by puzrin** [comment]
> This remapping is done by the font convertor. It's necessary because when UTF-8 is disabled, the symbols would be out of range since they use Unicode code points greater than one byte.
>
> If UTF-8 is enabled, then no special action would be needed on the convertor's part.

The most obvious thing would be to have 2 set of font files, for single-byte mapping, and for full range. Then select appropriate, based on `#define` value.

However, need to check real savings. Probably, it's very small and "utf8" version will be enougth.

**Comment by embeddedt** [comment]
The savings of having UTF-8 off are negligible, in my opinion. Most of the additional code size would be from the decoder logic in `lv_misc/lv_txt.c`. Plus, from my knowledge of internationalization, UTF-8 is almost mandatory, so I don't think it's a problem to permanently enable it.

**Comment by kisvegabor** [comment]
I removed `LV_TTX_UTF8` in `dev-6.0` and left the codes for the "enabled" version.

**Comment by puzrin** [comment]
Great!

I think, we need to discuss new font spec: font header, internals, and so on. Where is the best place for it?

In nearest days `lv_font_conv` will work with "dump" format.

- all cli options supported.
- output is directory with images + metadata.

This is special format for debugging, to check artefacts. Then we can start experiment with other writers and compression.

**Comment by kisvegabor** [comment]
Great! I suppose you opened https://github.com/littlevgl/lvgl/issues/990 to discuss it.

**Comment by puzrin** [comment]
Yes. Let's close this.

I could continue with binary format spec, but need your review first - about proposed features & approaches.
